name: Terraform CI (fmt + validate)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Terraform Fmt
        run: terraform fmt -check
      - name: Terraform Init (no backend)
        run: terraform init -backend=false -input=false
      - name: Terraform Validate
        run: terraform validate
